[project]
name = "innovative-decrypt-robot"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.user-authorization]
path = "contracts/user-authorization.clar"
depends_on = []

[contracts.asset-registry]
path = "contracts/asset-registry.clar"
depends_on = []

[contracts.geospatial-tracker]
path = "contracts/geospatial-tracker.clar"
depends_on = []

[contracts.audit-logger]
path = "contracts/audit-logger.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
